### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'ios_ver' when doing a pip install of a mobile forge whl

### ISSUE THREAD

**Issue by deva666** [beeware/mobile-forge#77] opened 2024-11-08 08:38 UTC
### Describe the bug

Trying to pip install a mobile forge built whl (any from the recipes) and getting this error:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 363, in run
    resolver = self.make_resolver(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 177, in make_resolver
    return pip._internal.resolution.resolvelib.resolver.Resolver(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 58, in __init__
    self.factory = Factory(
                   ^^^^^^^^
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 125, in __init__
    self._supported_tags_cache = get_supported()
                                 ^^^^^^^^^^^^^^^
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_internal/utils/compatibility_tags.py", line 165, in get_supported
    supported.extend(
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_vendor/packaging/tags.py", line 224, in cpython_tags
    platforms = list(platforms or platform_tags())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marko/Documents/Repos/mobile-forge/venv3.11/lib/python3.11/site-packages/pip/_vendor/packaging/tags.py", line 503, in ios_platforms
    _, release, _, _ = platform.ios_ver()  # type: ignore[attr-defined]
                       ^^^^^^^^^^^^^^^^
AttributeError: module 'platform' has no attribute 'ios_ver'
```

### Steps to reproduce

1. Pull latest mobile forge commit
2. Remove old venv folder
3. `source ./setup-iOS.sh 3.11`
4. `forge iOS`
5. All wheels from recipes build OK
6. `export PYTHONPATH=~/Documents/Repos/Python-Apple-support/support/3.11/iOS/platform-site/iphoneos.arm64/`
7. `python3 -u -X utf8 -m pip install --disable-pip-version-check --no-python-version-warning --upgrade --no-user --target=packages --find-links=~/Documents/Repos/mobile-forge/dist --find-links=~/Documents/Repos/mobile-forge/deps --find-links=~/Documents/Repos/mobile-forge/published --prefer-binary numpy-1.23.2-cp311-cp311-ios_13_0_arm64_iphoneos.whl`
8. The error  above pops up
9. Tried also `python3 -m pip install --force-reinstall pip==24.2` same error

### Expected behavior

pip installs correctly

### Environment

- Operating System: macOS 14.0
- Python version: 3.11
- Software versions:
  - Briefcase: -
  - Toga: -

**Comment by freakboy3742** [comment] 2024-11-09 02:28
Thanks for the report - I misunderstood your report on Discord. I thought this was an error in mobile-forge itself; but it's an error during the install of the wheels *after* they've been built.

The fact that downgrading to pip 24.2 doesn't fix this doesn't make sense to me - because pip 24.2 [doesn't have a reference to `ios_ver` on L503](https://github.com/pypa/pip/blob/24.2/src/pip/_vendor/packaging/tags.py#L503). I'm not sure what is going on with your setup, but the only way you would be getting "the same error" is if you have pip 24.3 or newer.

The other approach is to use the fact that pip now has native support for iOS, so you should be able to use:
```
python3 -m pip install --platform=ios_13_0_arm64_iphoneos --only-binary=:all: --find-links-... numpy-1.23.2-cp311-cp311-ios_13_0_arm64_iphoneos.whl
```
to explicitly pick the iOS platform. You need to use `--only-binary=:all:` - that means you won't be able to install any package that is published only as a `.tar.gz`. If it's a pure-python package published as a `.tar.gz`, you'll need to convert it into a `py3-none-any` wheel first.

If you're using Briefcase, then the issue is that you need to ensure you're using Briefcase to 0.3.20, and re-create your project - we've published updated templates and iOS support packages for Briefcase that address this issue.

**Comment by deva666** [comment] 2024-11-09 07:36
Thank you for the reply and your time for investigating this. I thought this was a mobile forge problem because I was running pip install from venv that mobile forge created. 
I exited the venv and upgraded the pip to latest version, exported the PYTHONPATH to point to ios sitecustomize.py and then tried your command `python3 -m pip install --platform=ios_13_0_arm64_iphoneos --only-binary=:all:` and it worked. 

But then when I copy this numpy package to the mobile app I get the following error 
```
Traceback (most recent call last): File /private/var/containers/Bundle/Application/DD419DA0-5D9C-4007-9213-C114E9625EB0/Runner.app/packages/numpy/core/__init__.py, line 49, in <module> 

raise ImportError(msg) ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. 
This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. 

We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html 

Please note and check the following: * The Python version is: Python3.11 from "/private/var/containers/Bundle/Application/DD419DA0-5D9C-4007-9213-C114E9625EB0/Runner.app/Runner" * 
The NumPy version is: "1.23.2" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help.

Original error was: No module named `numpy.core._multiarray_umath` 
```
Reading  https://numpy.org/devdocs/user/troubleshooting-importerror.html , maybe this could be the cause https://numpy.org/devdocs/user/troubleshooting-importerror.html#downstream-importerror-attributeerror-or-c-api-abi-incompatibility

But, I did check the numpy.core folder and there exists `_multiarray_umath.cpython-311-iphoneos.so` so that original error does not make sense

I know this is probably out of scope of mobile forge, but maybe you ran into same problem and have an idea what am I doing wrong?

**Comment by freakboy3742** [comment] 2024-11-10 23:03
> But, I did check the numpy.core folder and there exists `_multiarray_umath.cpython-311-iphoneos.so` so that original error does not make sense
> 
> I know this is probably out of scope of mobile forge, but maybe you ran into same problem and have an idea what am I doing wrong?

I'm going to guess you've installed an iPhone device wheel when you're running the app on the iPhone Simulator. If you're targeting the simulator, the `pip` invocation should be using `--platform=ios_13_0_arm64_iphonesimulator`, and the .so file should be `_multiarray_umath.cpython-311-iphonesimulator.so`. If you try to use an iPhone device binary on the simulator, raising errors about not being able to find the binary would be one possible manifestation.

**Comment by freakboy3742** [comment] 2024-11-10 23:05
I'm going to close this ticket on the basis that the error doesn't appear to be in Mobile Forge. If you have continued issues, I'm happy to continue providing pointers here, or in Discord, or a discussion thread.

**Closed by freakboy3742** 2024-11-10 23:05 UTC
Labels: bug
